<a href="https://colab.research.google.com/github/guljahonabdusalomova/week3_lab/blob/main/exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals Exercises

This notebook contains exercises based on the PyTorch Fundamentals tutorial. Each section corresponds to a topic from the original notebook. Complete the exercises by filling in the code cells where indicated.

## 1. Introduction to Tensors

### Exercise 1.1: Create a scalar tensor
Create a scalar tensor with the value 42 and print its value, number of dimensions (ndim), and shape.

In [1]:
import torch

# TODO: Create a scalar tensor
scalar = torch.tensor(7)

# Print details
print(scalar)
print(f"Number of dimensions: {scalar.ndim}")
print(f"Shape: {scalar.shape}")

tensor(7)
Number of dimensions: 0
Shape: torch.Size([])


### Exercise 1.2: Create a vector tensor
Create a vector tensor with values [1, 2, 3, 4] and print its value, ndim, and shape.

In [2]:
# TODO: Create a vector tensor
vector = torch.tensor([7, 7])

# Print details
print(vector)
print(f"Number of dimensions: {vector.ndim}")
print(f"Shape: {vector.shape}")

tensor([7, 7])
Number of dimensions: 1
Shape: torch.Size([2])


### Exercise 1.3: Create a matrix tensor
Create a 2x3 matrix tensor with values [[1, 2, 3], [4, 5, 6]] and print its details.

In [3]:
# TODO: Create a matrix tensor
matrix = torch.tensor([[5, 9],
                       [9, 11]])

# Print details
print(matrix)
print(f"Number of dimensions: {matrix.ndim}")
print(f"Shape: {matrix.shape}")

tensor([[ 5,  9],
        [ 9, 11]])
Number of dimensions: 2
Shape: torch.Size([2, 2])


### Exercise 1.4: Create a 3D tensor
Create a tensor of shape (2, 2, 2) with sequential values from 1 to 8 using torch.arange and reshape.

In [4]:
# TODO: Create a 3D tensor
tensor_3d = torch.tensor([[[1, 2, 3],
                        [3, 8, 9],
                        [12, 4, 5]]])

# Print details
print(tensor_3d)
print(f"Number of dimensions: {tensor_3d.ndim}")
print(f"Shape: {tensor_3d.shape}")

tensor([[[ 1,  2,  3],
         [ 3,  8,  9],
         [12,  4,  5]]])
Number of dimensions: 3
Shape: torch.Size([1, 3, 3])


## 2. Random Tensors

### Exercise 2.1: Create a random tensor
Create a random tensor of shape (4, 4) and print it along with its dtype.

In [6]:
# TODO: Create random tensor
random_tensor = torch.rand(size=(2, 4))

print(random_tensor)
print(f"Datatype: {random_tensor.dtype}")

tensor([[0.5423, 0.3910, 0.8018, 0.7730],
        [0.7676, 0.3311, 0.5131, 0.6603]])
Datatype: torch.float32


### Exercise 2.2: Create an image-sized random tensor
Create a random tensor of shape (3, 224, 224) simulating an image (channels, height, width).

In [32]:
# TODO: Create image-sized random tensor
image_tensor = torch.rand(2,7,10)

print(f"Shape: {image_tensor.shape}")

Shape: torch.Size([2, 7, 10])


## 3. Zeros and Ones

### Exercise 3.1: Create a tensor of zeros
Create a tensor of zeros with shape (5, 5).

In [33]:
# TODO: Create zeros tensor
zeros = torch.zeros(12,14,35)

## 4. Creating Ranges

### Exercise 4.1: Create a range tensor
Create a tensor with values from 0 to 20 with a step of 2 using torch.arange.

In [34]:
# TODO: Create range tensor
range_tensor = torch.zeros(56,34,23)

## 5. Tensor Datatypes

### Exercise 5.1: Create tensors with specific dtypes
Create a tensor with values [1.0, 2.0, 3.0] using dtype=torch.float16 and another with dtype=torch.int64.

### Exercise 5.2: Change dtype
Convert the float16_tensor to float32.

In [38]:
# TODO: Change dtype
float16_tensor = torch.tensor([1.0, 2.0, 3.0],dtype=torch.float16)

## 6. Getting Information from Tensors

### Exercise 6.1: Print tensor info
Create a random tensor of shape (2, 3, 4) and print its shape, dtype, and device.

In [20]:
# TODO: Create tensor and print info
info_tensor = [1.0, 2.0, 3.0]

## 7. Manipulating Tensors (Basic Operations)

### Exercise 7.1: Perform basic operations
Create a tensor [10, 20, 30]. Add 5, subtract 10, multiply by 2, and divide by 10.

In [26]:
tensor = torch.tensor([10, 20, 30])
# TODO: Add 5
tensor + 5


tensor([15, 25, 35])

In [27]:
# TODO: Subtract 10
tensor-10

tensor([ 0, 10, 20])

In [28]:
# TODO: Multiply by 2
tensor*2

tensor([20, 40, 60])

In [29]:
# TODO: Divide by 10
tensor/10

tensor([1., 2., 3.])

### Exercise 7.2: Matrix multiplication
Create two tensors A (2x3) and B (3x2) with random values and perform matrix multiplication.

In [50]:
# TODO: Create A and B
A = torch.rand(2,3)
B = torch.rand(3,2)

# TODO: Matrix mul using torch.mm
result_mm = torch.mm(A,B)
print(result_mm)
# TODO: Matrix mul using @
result_at =A @ B
print(result_at)

tensor([[0.2350, 0.6016],
        [0.2233, 0.4052]])
tensor([[0.2350, 0.6016],
        [0.2233, 0.4052]])



## 8. Tensor Aggregation

### Exercise 8.1: Find min, max, mean, sum
Create a tensor with values from 0 to 100 and find its min, max, mean, and sum.

In [55]:
agg_tensor = torch.arange(0, 101)
# TODO: Min
print(f"Index where min value occurs: {tensor.argmin()}")
# TODO: Max
print(f"Index where max value occurs: {tensor.argmax()}")
# TODO: Mean (note: may need to cast to float)
print(f"Mean: {tensor.float().mean()}")
# TODO: Sum
print(f"Sum: {tensor.sum()}")

Index where min value occurs: 0
Index where max value occurs: 2
Mean: 20.0
Sum: 60


### Exercise 8.2: Argmin and argmax
Find the positions of the minimum and maximum values in the above tensor.

In [56]:
tensor = torch.arange(0, 101)
# TODO: Argmin
min_index = tensor.argmin()
print(f"Index of min value: {min_index}")
# TODO: Argmax
max_index = tensor.argmax()
print(f"Index of max value: {max_index}")

Index of min value: 0
Index of max value: 100


## 9. Reshaping, Stacking, Squeezing, Unsqueezing

### Exercise 9.1: Reshape a tensor
Create a tensor of shape (10,) and reshape it to (2, 5).

In [59]:
reshape_tensor = torch.arange(10)
# TODO: Reshape
reshaped = reshape_tensor = torch.arange(10)
reshaped = reshape_tensor.reshape(2, 5)

print("Original tensor:", reshape_tensor)
print("Reshaped tensor (2,5):\n", reshaped)


Original tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Reshaped tensor (2,5):
 tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


### Exercise 9.2: Stack tensors
Create two tensors of shape (2, 2) and stack them vertically and horizontally.

In [60]:
tensor1 = torch.rand(2, 2)
tensor2 = torch.rand(2, 2)
# TODO: Stack vertically (dim=0)
vertical_stack = torch.cat((tensor1, tensor2), dim=0)
print("Vertical stack (dim=0):\n", vertical_stack)
# TODO: Stack horizontally (dim=1)
horizontal_stack = torch.cat((tensor1, tensor2), dim=1)
print("Horizontal stack (dim=1):\n", horizontal_stack)

Vertical stack (dim=0):
 tensor([[0.3406, 0.9116],
        [0.4706, 0.1828],
        [0.5109, 0.0592],
        [0.1734, 0.2105]])
Horizontal stack (dim=1):
 tensor([[0.3406, 0.9116, 0.5109, 0.0592],
        [0.4706, 0.1828, 0.1734, 0.2105]])


### Exercise 9.3: Squeeze and unsqueeze
Create a tensor of shape (1, 3, 1), squeeze it, then unsqueeze it back on dim=0.

In [ ]:
squeeze_tensor = torch.rand(1, 3, 1)
# TODO: Squeeze
squeezed =

# TODO: Unsqueeze on dim=0
unsqueezed =

### Exercise 9.4: Permute
Create an image tensor (3, 100, 100) and permute it to (100, 100, 3).

In [62]:
image_tensor = torch.rand(3, 100, 100)
# TODO: Permute
permuted = permuted = image_tensor.permute(1, 2, 0)
print("Original shape:", image_tensor.shape)
print("Permuted shape:", permuted.shape)

Original shape: torch.Size([3, 100, 100])
Permuted shape: torch.Size([100, 100, 3])


## 10. Indexing

### Exercise 10.1: Index into a tensor
Create a tensor [[[1,2,3],[4,5,6],[7,8,9]]] and index to get 5, then the entire second row.

In [63]:
index_tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
# TODO: Get 5
value_5 = index_tensor[0, 1, 1]  # batch 0, row 1, column 1
print("Value 5:", value_5)

# TODO: Get second row [4,5,6]
second_row = index_tensor[0, 1, :]  # batch 0, row 1, all columns
print("Second row:", second_row)

Value 5: tensor(5)
Second row: tensor([4, 5, 6])


## 11. PyTorch and NumPy

### Exercise 11.1: NumPy to PyTorch
Create a NumPy array [1,2,3,4] and convert it to a PyTorch tensor.

In [64]:
import numpy as np
numpy_array = np.array([1,2,3,4])
# TODO: Convert to tensor
from_numpy = torch.from_numpy(numpy_array)
print("NumPy array:", numpy_array)
print("PyTorch tensor:", from_numpy)

NumPy array: [1 2 3 4]
PyTorch tensor: tensor([1, 2, 3, 4])


### Exercise 11.2: PyTorch to NumPy
Create a PyTorch tensor [5,6,7,8] and convert it to a NumPy array.

In [65]:
pytorch_tensor = torch.tensor([5,6,7,8])
# TODO: Convert to NumPy
to_numpy = pytorch_tensor.numpy()

print("PyTorch tensor:", pytorch_tensor)
print("NumPy array:", to_numpy)

PyTorch tensor: tensor([5, 6, 7, 8])
NumPy array: [5 6 7 8]


## 12. Reproducibility

### Exercise 12.1: Set manual seed
Set the manual seed to 77 and create two random tensors of shape (2,2). Check if they are equal.

In [66]:
# TODO: Set seed
torch.manual_seed(77)
rand1 = torch.rand(2,2)

# TODO: Reset seed for second tensor

rand2 = torch.rand(2,2)

# Check equality
print(rand1 == rand2)
print("First tensor:\n", rand1)
print("Second tensor:\n", rand2)
print("Are they equal?\n", rand1 == rand2)

tensor([[False, False],
        [False, False]])
First tensor:
 tensor([[0.2919, 0.2857],
        [0.4021, 0.4645]])
Second tensor:
 tensor([[0.9503, 0.2564],
        [0.6645, 0.8609]])
Are they equal?
 tensor([[False, False],
        [False, False]])


## 13. Running on GPUs

### Exercise 13.1: Check for GPU
Write code to check if CUDA is available and set the device accordingly.

In [67]:
# TODO: Set device
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

Device: cpu


### Exercise 13.2: Move tensor to GPU
Create a tensor and move it to the GPU if available. Then move it back to CPU and convert to NumPy.

In [68]:
gpu_tensor = torch.tensor([10, 20, 30])
# TODO: Move to device
gpu_tensor = gpu_tensor.to(device)

# TODO: Move back to CPU and to NumPy
cpu_numpy = gpu_tensor.cpu().numpy()